services:
  postgres:
    image: postgres:16
    container_name: coursesphere-db
    environment:
      POSTGRES_DB: coursesphere
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ../../BackEnd
      dockerfile: ../Infra/docker/BackEnd/Dockerfile
    container_name: coursesphere-backend
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/coursesphere
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    volumes:
      - ../../BackEnd/seed-data:/app/seed-data
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ../../FrontEnd/VlabFront
      dockerfile: ../../Infra/docker/FrontEnd/Dockerfile
    container_name: coursesphere-frontend
    depends_on:
      - backend
    environment:
      # ATENÇÃO: isso só funciona se o browser acessar esse host.
      # Para dev local, prefira http://localhost:8080
      VITE_API_URL: http://localhost:8080
    ports:
      - "5173:5173"

volumes:
  postgres_data: